### ISSUE TITLE
2021 July - People of WordPress

### ISSUE THREAD

**Issue by murillol** [wpmarketingteam/Marcomms-Series#11]
**Name**: Yordan Soares
**Continent**: South America
**Country**: Venezuela
**HeroPress Link**: https://heropress.com/essays/beyond-software-meeting-the-wordpress-community/
[Working Document](https://docs.google.com/document/d/1zFvayML6X5YQL4eJfW3SQEJfa_3eShWomxx_GGlUhro/edit?usp=sharing)

- [x] Draft 1 Assigned to: Maedah
- [x] Second Editor: Larissa
- [ ] Final Editors: Abha and Chloe
- [ ] Images: Maedah
- [ ] Search: Larissa
- [ ] Liasion: Larissa

**Comment by abhansnuk** [comment]
Progress update request: @murillol and Maedah

**Comment by murillol** [comment]
> Progress update request: @murillol and Maedah

I am ready to take a look at the draft but the working document is empty. Will ask Maedah what happened and update.

**Comment by murillol** [comment]
> > Progress update request: @murillol and Maedah
> 
> I am ready to take a look at the draft but the working document is empty. Will ask Maedah what happened and update.

Update: spoken with Maedah and she had a bit of a delay but is currently working on it and hopes to have it by this week.

**Comment by abhansnuk** [comment]
As we have not been able to publish this one for a link with translation day. Is there an alternative which could be used and ready to publish by Monday or are we likely to have this draft for final editing by 9 September please @murillol  ? Thanks for your help with this.

**Comment by murillol** [comment]
> As we have not been able to publish this one for a link with translation day. Is there an alternative which could be used and ready to publish by Monday or are we likely to have this draft for final editing by 9 September please @murillol ? Thanks for your help with this.

Even if Maedah gets it to us by tomorrow it would still have to go through an editing round so I would say it will **not** be ready by 9 September. I can't see a few of the documents on Drive (October, November, December) but I did see that both Maedah and Alison seemed to have advanced plenty on the PoW profile corresponding to Maedah (I think it was the one due for May). Maybe we could go with that one @abhansnuk?

**Comment by murillol** [comment]
**Update**: Maedah has shared the first draft with me and Nalini today (in a private Google Document), and there are some updates pending from Yordan. I am leaving any edits as suggestions in that doc, and as soon as I can, I will put the second draft in the 'official' shared doc, linked above.

**Comment by murillol** [comment]
**Update:** I have put my edits in suggestion mode and they are ready for @abhansnuk to take a look at. We do not have images (the ones in the original article are group photos) so I am asking Yordan to provide.

**Comment by abhansnuk** [comment]
Update summary
Done in the last week:
- further writing/ edit by Larissa and Nalini
- bringing in quotes/ edit by Abha
- final edits and checks by Chloe
- pictures edited by Meher
- linked in with Hari and WPTD, final review on WPTD, final review on News (with Hari and Meher)
- copied to P2, publishing display edits, Twitter and Facebook, Featured Image, and Test. Published with International Translation Day 30 September 2021
- Nomination graphic from WPTD added by Hari once produced, Updated published post. Shared with WCUS
- Abha sent links to Topher

To do:
- To be reshared on social once link to nominations up on WPTD and include #ContributorStory in promotions
- HeroPress will then share it out again

**Comment by OlaIola** [comment]
Russian translation: https://ru.wordpress.org/news/2021/10/people-of-wordpress-yordan-soares/
