### ISSUE TITLE
2021 November - People of WordPress

### ISSUE THREAD

**Issue by abhansnuk** [wpmarketingteam/Marcomms-Series#24]
Devin Maeztri
Scheduled for either October or November 2021 to be able to cross-link with WPTD nomination story. 

Original source material https://heropress.com/essays/wordpress-and-me-am-i-going-against-all-odds/

**Comment by abhansnuk** [comment]
Nalini suggested change in schedule for publication. Confirmed with Chloe B 2021/10/04 
Reasons:
- cross-link it to WPTranslationDay follow-up stories and as the Indonesian community achieved a lot relating to translation of releases
- cross-link to Polyglot appreciation nominees once published (she has given permission for the publication)
- involved with the WPDiversity, and opportunities to cross-promote the diversity initiatives 
- awaiting a number of drafts on other features, which will need rescheduled publication dates
- works well with the balance of the series

**Comment by abhansnuk** [comment]
- [x] Factual Update: 
- [x]  Draft 1 Assigned to: Nalini / Abha
- [x]  Second Editor: Nalini, Meher
- [x]  Final Series Editors: Abha and Chloe
- [x]  Liasion: Abha initial, then handed over to Nalini
- [ ] Search / meta: Larissa
- [x] Images: To try and find original ones Abha took at WCEU

**Comment by abhansnuk** [comment]
Images: Meher
Writing & Editing: Abha, Mary Baum
Social (Jetpack): Abha
Testing: Meher
Final review: Chloe, Collieth
Testing: Meher

Published: https://wordpress.org/news/2021/11/people-of-wordpress-devin-maeztri/ 

Twitter: https://twitter.com/WordPress/status/1465808235567501315?s=20
The latest People of WordPress features Devin Maeztri, a translator and campaigner from #Indonesia who uses #WordPress to highlight good causes. #ContributorStory

**Comment by oglekler** [comment]
This article is translated to Russian: https://ru.wordpress.org/news/2021/12/people-of-wordpress-devin-maeztri/
