### ISSUE TITLE
2022 August - People of WordPress

### ISSUE THREAD

**Issue by murillol** [wpmarketingteam/Marcomms-Series#7]
**Name**: Maedah Batool
**Continent**: Asia 
**Country**: Pakistan
**HeroPress Link**: https://heropress.com/essays/making-wordpress-journalist/
[Working Document](https://docs.google.com/document/d/1ORut1J16WJyCqoO0_TyqIlS72XQxcY92ZlpmFYHz-HU/edit?usp=sharing)

- [x] Factual Update: Maedah
- [ ] Draft 1 Assigned to: Alison (Yvette liaising)
- [ ] Second Editor: Nalini
- [ ] Final Series Editors: Abha and Chloe
- [ ] Liasion: Yvette
- [ ] Search / meta: Larissa
- [ ] Images: Olga

**Comment by nalininsbs** [comment]
This is now scheduled for the November 2022 edition.

**Comment by nalininsbs** [comment]
[Google document](https://docs.google.com/document/d/1ORut1J16WJyCqoO0_TyqIlS72XQxcY92ZlpmFYHz-HU/edit?usp=sharing) - there are a number of queries that need to be checked with Maedah including items for updating. Last week, contact was remade with Maedah from messages. Date to be confirmed for a call to go through these.

**Comment by nalininsbs** [comment]
Sorry I seem to have updated the old card on the old GitHub. @abhansnuk or @meherbala can you please help?

**Comment by abhansnuk** [comment]
Copied over your last two comments to the card on the new repo.
